{"name": "Тест на ошибку при  авторизации под несуществующим пользователем", "status": "passed", "description": "Вводим логин и пароль несуществующего курьера и проверяем что получаем ошибку 404 и сообщение \"Учетная запись не найдена\"", "start": 1745008119356, "stop": 1745008119471, "uuid": "a643a0fa-580a-44e3-9896-7af444fcdda5", "historyId": "8cf5a2d34ff37b3330879f24c96204ff", "testCaseId": "8cf5a2d34ff37b3330879f24c96204ff", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_with_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}