{"name": "Тест на получение ошибки приняти заказа без id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_accept_the_order.TestAcceptOrder object at 0x00000271BB67F230>\ngenerate_courier_data = [{'firstName': 'Tara', 'login': 'dOrPi', 'password': 4768}, 'dOrPi', 4768]\n\n    @allure.title('Тест на получение ошибки приняти заказа без id заказа')\n    def test_accept_order_without_order_id(self, generate_courier_data):\n        # Создаем курьера и получаем его ID\n        CourierMethods.create_courier(generate_courier_data[0])\n        courier_id = CourierMethods.get_courier_id(generate_courier_data[1], generate_courier_data[2])\n        accept_response = OrdersMethods.accept_order(order_id='',courier_id=courier_id)\n>       assert accept_response.status_code == 400 and accept_response.json().get(\n            \"message\") == \"Недостаточно данных для поиска\"\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_accept_the_order.py:41: AssertionError"}, "start": 1745072122633, "stop": 1745072123215, "uuid": "fe91f2fa-95a5-4ed7-bd9d-55bcc4acec81", "historyId": "45917850ef452acf5bc3ca8dbd98ece2", "testCaseId": "45917850ef452acf5bc3ca8dbd98ece2", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_without_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "10504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}