{"name": "Тест на ошибку при  авторизации под несуществующим пользователем", "status": "passed", "description": "Вводим логин и пароль несуществующего курьера и проверяем что получаем ошибку 404 и сообщение \"Учетная запись не найдена\"", "start": 1745072128943, "stop": 1745072129495, "uuid": "ced39e39-69f7-4ac3-a612-8902dda525c1", "historyId": "8cf5a2d34ff37b3330879f24c96204ff", "testCaseId": "8cf5a2d34ff37b3330879f24c96204ff", "fullName": "tests.test_login_courier.TestLoginCourier#test_auth_with_invalid_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "10504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}