{"name": "Тест на получение ошибки приняти заказа без id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.test_accept_the_order.TestAcceptOrder object at 0x00000192A0CCF230>\ngenerate_courier_data = [{'firstName': 'Michael', 'login': 'NEmVO', 'password': 4695}, 'NEmVO', 4695]\n\n    @allure.title('Тест на получение ошибки приняти заказа без id заказа')\n    def test_accept_order_without_order_id(self, generate_courier_data):\n        # Создаем курьера и получаем его ID\n        CourierMethods.create_courier(generate_courier_data[0])\n        courier_id = CourierMethods.get_courier_id(generate_courier_data[1], generate_courier_data[2])\n        accept_response = OrdersMethods.accept_order(order_id='',courier_id=courier_id)\n>       assert accept_response.status_code == 400 and accept_response.json().get(\n            \"message\") == \"Недостаточно данных для поиска\"\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\test_accept_the_order.py:42: AssertionError"}, "start": 1745008113113, "stop": 1745008113490, "uuid": "c7d67429-1b79-456c-9c0b-b2ad46a5c2d6", "historyId": "45917850ef452acf5bc3ca8dbd98ece2", "testCaseId": "45917850ef452acf5bc3ca8dbd98ece2", "fullName": "tests.test_accept_the_order.TestAcceptOrder#test_accept_order_without_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_the_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-3QFAQEQR"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_the_order"}]}